<a href="https://colab.research.google.com/github/AdiBhushan10/My-Leetcode-Practice/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to tensors

In [4]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [5]:
# create tesnor using constant
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
scalar.ndim

0

In [8]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
vector.ndim

1

In [12]:
matrix = tf.constant([[10,10],[20,20]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [20, 20]], dtype=int32)>

In [13]:
matrix.ndim

2

In [14]:
# create tesnor using Variable
changeable_tensor = tf.Variable([10,20])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 20], dtype=int32)>

In [16]:
changeable_tensor[1]

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [18]:
changeable_tensor[0].assign(200)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([200,  20], dtype=int32)>

In [20]:
# create random variables
random1 = tf.random.Generator.from_seed(1)   # set seed for reproduceability
random1 = random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.43842274, -0.53439844],
       [-0.07710262,  1.5658046 ],
       [-0.1012345 , -0.2744976 ]], dtype=float32)>